<?= $this->include('themes/madya/layouts/header') ?>
<?php $banner=!empty($page_banners)?(json_decode($page_banners,true)['downloads']??[]):[]; $allItems=[]; foreach (($categories??[]) as $group) foreach ($group as $item) $allItems[]=$item; $categoryCount=count($categories??[]); ?>
<?= $this->include('themes/madya/components/page-header', ['eyebrow'=>$banner['badge']??'Pusat Dokumen', 'title'=>$banner['title']??'Dokumen Resmi', 'description'=>$banner['subtitle']??'Formulir, panduan, dan dokumen resmi sekolah dalam satu tempat.', 'image'=>$allItems[0]['image']??'', 'breadcrumbs'=>[['label'=>'Dokumen']]]) ?>
<section class="section"><div class="theme-container">
    <div class="download-stat-grid"><div class="download-stat"><strong><?= count($allItems) ?></strong><span>Total dokumen</span></div><div class="download-stat"><strong><?= $categoryCount ?></strong><span>Kategori</span></div><div class="download-stat"><strong><?= count(array_filter($allItems, static fn($i)=>strtolower((string)($i['extension']??pathinfo((string)($i['url']??''),PATHINFO_EXTENSION)))==='pdf')) ?></strong><span>Dokumen PDF</span></div><div class="download-stat"><strong>—</strong><span>Dokumen populer</span></div></div>
    <div class="downloads-toolbar"><form class="news-search" method="get" action="<?= base_url('downloads') ?>"><label class="sr-only" for="download-search">Cari dokumen</label><input id="download-search" name="search" placeholder="Cari dokumen…"><button class="button" type="submit">Cari</button></form><select aria-label="Urutkan dokumen"><option>Terbaru</option><option>Nama A-Z</option></select></div>
    <div class="download-layout"><div><?php if ($categories): foreach ($categories as $category=>$items): ?><section class="document-group"><div class="document-group-heading"><div><p class="eyebrow">Koleksi</p><h2><?= esc($category ?: 'Dokumen lainnya') ?></h2></div><span><?= count($items) ?> berkas</span></div><div class="document-list"><?php foreach ($items as $item): ?><?= $this->include('themes/madya/components/content/download-item', ['item'=>$item]) ?><?php endforeach; ?></div></section><?php endforeach; else: ?><?= $this->include('themes/madya/components/ui/empty-state', ['message'=>'Belum ada dokumen yang tersedia untuk diunduh.']) ?><?php endif; ?></div>
    <aside class="download-sidebar"><h2>Kategori</h2><?php foreach ($categories as $category=>$items): ?><a href="#"><?= esc($category ?: 'Dokumen lainnya') ?><span><?= count($items) ?></span></a><?php endforeach; ?><a href="<?= base_url('contact') ?>">Butuh bantuan?</a></aside></div>
</div></section>
<?= $this->include('themes/madya/layouts/footer') ?>
