import {
    Activity,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    BookOpen,
    CalendarDays,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleHelp,
    Clock3,
    GraduationCap,
    Image as ImageIcon,
    Landmark,
    Mail,
    MapPin,
    Monitor,
    Menu,
    MessageCircle,
    Megaphone,
    MonitorPlay,
    BellRing,
    Download,
    FileText,
    PlayCircle,
    Target,
    Phone,
    Send,
    UserPlus,
    Microscope,
    Music,
    Palette,
    Quote,
    School,
    Search,
    Sparkles,
    Trophy,
    Users,
    X,
    createIcons,
} from 'lucide';

const icons = {
    activity: Activity,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-up-right': ArrowUpRight,
    'book-open': BookOpen,
    'calendar-days': CalendarDays,
    check: Check,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'circle-help': CircleHelp,
    'clock-3': Clock3,
    'megaphone': Megaphone,
    'monitor-play': MonitorPlay,
    'bell-ring': BellRing,
    'download': Download,
    'file-text': FileText,
    'play-circle': PlayCircle,
    target: Target,
    'phone': Phone,
    'send': Send,
    'user-plus': UserPlus,
    'graduation-cap': GraduationCap,
    'image': ImageIcon,
    landmark: Landmark,
    mail: Mail,
    'map-pin': MapPin,
    monitor: Monitor,
    menu: Menu,
    'message-circle': MessageCircle,
    microscope: Microscope,
    palette: Palette,
    quote: Quote,
    school: School,
    search: Search,
    sparkles: Sparkles,
    trophy: Trophy,
    users: Users,
    x: X,
    flask: Microscope,
    book: BookOpen,
    calendar: CalendarDays,
    sparkle: Sparkles,
    compass: School,
    running: Activity,
    globe: Landmark,
    'hand-heart': Sparkles,
    'laptop-code': Monitor,
    microchip: Activity,
    music: Music,
    futbol: Trophy,
    'paint-brush': Palette,
    leaf: Sparkles,
    medal: Trophy,
    award: Trophy,
    'quote-left': Quote,
    'user-graduate': GraduationCap,
    'chalkboard-teacher': Users,
};

export function iconMarkup(name, className = '') {
    return `<i class="${className}" data-lucide="${String(name || 'sparkles')}" aria-hidden="true"></i>`;
}

export function initIcons(root = document) {
    const hosts = root.querySelectorAll?.('[data-lucide]');
    if (!hosts?.length) return;
    createIcons({
        icons,
        attrs: {
            'stroke-width': 1.7,
            'aria-hidden': 'true',
        },
    });
}
