import { iconMarkup } from '../icons.js';

export default function renderHome(state, container) {
  const programs = state.programs || [], teachers = state.teachers || [], achievements = state.achievements || [], news = state.news || [], events = state.events || [], galleries = state.galleries || [], testimonials = state.testimonials || [], principal = state.principal || teachers[0] || {}, about = state.about || {}, downloads = state.downloads || [];
  const announcements = (news.filter(x => String(x.category || '').toLowerCase() === 'pengumuman').length ? news.filter(x => String(x.category || '').toLowerCase() === 'pengumuman') : news).slice(0, 3);
  const services = [
    ['user-plus', 'SPMB Online', 'Pendaftaran siswa baru', state.spmb_url || '#'],
    ['monitor-play', 'E-Learning', 'Belajar di mana saja', '#'],
    ['book-open', 'Perpustakaan', 'Akses buku & referensi', '#'],
    ['bell-ring', 'Pengaduan', 'Sampaikan keluhan Anda', '#'],
    ['download', 'Download Dokumen', 'Formulir & surat penting', '/downloads'],
    ['mail', 'Kontak Sekolah', 'Hubungi kami', '/contact'],
  ];
  const statIcons = ['users', 'graduation-cap', 'trophy', 'book-open'];
  const imageOr = (src, alt, item = {}) => src ? `<img src="${esc(src)}" width="${esc(item.image_width || item.width || 1600)}" height="${esc(item.image_height || item.height || 1000)}" alt="${esc(alt)}" loading="lazy" decoding="async">` : `<div class="media-placeholder" role="img" aria-label="${esc(alt)}"><span>${esc(alt)}</span></div>`;
  const date = (value) => value ? new Date(value).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }) : '';
  const month = (value) => value ? new Date(value).toLocaleDateString('id-ID', { month: 'short' }).toUpperCase() : '';
  const heroTitle = esc(state.hero_title || 'Membentuk Generasi Berilmu, Berakhlak, dan Berprestasi.').replace(/(Berprestasi\.?)(\s*)$/u, '<span class="hero-title-accent">$1</span>$2');

  container.innerHTML = `<div class="home-page">
    <section class="home-hero" aria-labelledby="hero-title"><div class="theme-container home-hero-grid"><div class="home-hero-copy">${state.hero_badge ? `<p class="hero-kicker">${esc(state.hero_badge)}</p>` : ''}<h1 id="hero-title">${heroTitle}</h1><p class="hero-lead">${esc(state.hero_subtitle || state.site_description || state.site_tagline || '')}</p><div class="home-hero-actions"><a class="button" href="#profile">Jelajahi Sekolah ${iconMarkup('arrow-right')}</a><a class="button button-secondary" href="#profile">${iconMarkup('play-circle')} Tentang Kami</a></div></div><div class="hero-photo-wrap"><figure class="hero-photo">${imageOr(about.hero_image || about.image, `Lingkungan ${state.site_name || 'sekolah'}`, about)}</figure>${announcements.length ? `<aside class="hero-announcement"><h2>${iconMarkup('megaphone')} Pengumuman Terbaru</h2><ul class="announcement-list">${announcements.map(x => `<li><a href="/news/${encodeURIComponent(x.slug || '')}">${esc(x.title || 'Informasi terbaru')}</a><small>${esc(date(x.published_at))}</small></li>`).join('')}</ul><a class="announcement-more" href="/news?category=Pengumuman">Lihat semua pengumuman ${iconMarkup('arrow-right')}</a></aside>` : ''}</div></div></section>
    <section class="home-quick-services" aria-label="Layanan cepat"><div class="theme-container quick-service-grid">${services.map(([i, l, d, u]) => `<a class="quick-service${u === '#' ? ' is-disabled' : ''}" href="${esc(u)}"${u === '#' ? ' aria-disabled="true" tabindex="-1"' : ''}><span class="quick-service-icon">${iconMarkup(i)}</span><span><strong>${esc(l)}</strong><small>${esc(d)}</small></span></a>`).join('')}</div></section>
    ${state.counter_stats?.length ? `<section class="home-stat-section" aria-label="Statistik sekolah"><div class="theme-container"><div class="home-stat-grid">${state.counter_stats.slice(0, 4).map((x, i) => `<div class="home-stat-item">${iconMarkup(statIcons[i] || 'sparkles')}<div><strong>${esc(x.value || x.number || '')}</strong><span>${esc(x.label || x.title || '')}</span></div></div>`).join('')}</div></div></section>` : ''}
    <section class="home-section" id="profile" aria-labelledby="profile-title"><div class="theme-container profile-grid"><article class="principal-panel"><div class="principal-photo">${imageOr(principal.image || principal.image_url, principal.name || 'Kepala sekolah', principal)}</div><div class="principal-message"><p class="section-kicker">Sambutan Kepala Sekolah</p><blockquote>“${esc(principal.bio || '')}”</blockquote><strong>${esc(principal.name || 'Kepala Sekolah')}</strong><span>${esc(principal.title || principal.position || 'Kepala Sekolah')}</span></div></article><div class="profile-copy"><p class="section-kicker">Profil Singkat</p><h2 id="profile-title">Sekolah yang tumbuh bersama masyarakat.</h2><p>${esc(about.description || state.site_description || '')}</p><div class="profile-points"><div class="profile-point">${iconMarkup('compass')}<div><strong>Visi</strong><span>${esc(about.visi || '')}</span></div></div><div class="profile-point">${iconMarkup('target')}<div><strong>Misi</strong><span>${esc(about.misi || '')}</span></div></div><div class="profile-point">${iconMarkup('landmark')}<div><strong>Fasilitas Unggulan</strong><span>${esc(about.facilities || '')}</span></div></div></div><a class="text-link" href="#profile">Selengkapnya Tentang Sekolah ${iconMarkup('arrow-right')}</a></div></div></section>
    ${(programs.length || (state.extracurriculars || []).length) ? `<section class="home-section section-soft" id="programs"><div class="theme-container"><div class="section-head-row"><div><p class="section-kicker">Program & Ekstrakurikuler</p><h2>Wadah pengembangan potensi dan minat siswa.</h2></div><a class="text-link" href="#programs">Lihat Semua ${iconMarkup('arrow-right')}</a></div><div class="programs-extras-grid"><div><div class="subsection-label"><span>Program Unggulan</span></div><div class="program-card-grid">${programs.slice(0, 4).map(x => `<article class="program-card"><span class="program-card-icon">${iconMarkup(x.icon || 'book-open')}</span><h3>${esc(x.title || x.name || 'Program')}</h3><p>${esc(x.description || '')}</p></article>`).join('')}</div></div><div><div class="subsection-label"><span>Ekstrakurikuler Populer</span><a href="#programs">Lihat Semua ${iconMarkup('arrow-right')}</a></div><div class="extra-rail">${(state.extracurriculars || []).slice(0, 6).map(x => `<a class="extra-card" href="#programs">${x.image ? `<img src="${esc(x.image)}" alt="" loading="lazy">` : ''}<span>${esc(x.title || x.name || 'Kegiatan')}</span></a>`).join('')}</div></div></div></div></section>` : ''}
    ${(teachers.length || achievements.length) ? `<section class="home-section" id="teachers"><div class="theme-container people-achievements-grid">${teachers.length ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Tenaga Pengajar</p><h2>Guru profesional dan berkompeten.</h2></div><a class="text-link" href="#teachers">Lihat Semua ${iconMarkup('arrow-right')}</a></div><div class="teacher-grid">${teachers.slice(0, 4).map(x => `<article class="teacher-card">${x.image ? imageOr(x.image, x.name || 'Tenaga pendidik', x) : ''}<div><strong>${esc(x.name || 'Tenaga pendidik')}</strong><span>${esc(x.title || x.position || 'Tenaga pendidik')}</span></div></article>`).join('')}</div></div>` : ''}${achievements.length ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Prestasi Siswa</p><h2>Mengukir prestasi di berbagai bidang.</h2></div><a class="text-link" href="#achievements">Lihat Semua ${iconMarkup('arrow-right')}</a></div><div class="achievement-cards" id="achievements">${achievements.slice(0, 3).map(x => `<article class="achievement-card">${x.image ? `<img src="${esc(x.image)}" alt="" loading="lazy">` : ''}<span class="achievement-level">${esc(x.level || 'Prestasi')}</span><div><small>${esc(x.year || '')}</small><h3>${esc(x.title || 'Prestasi siswa')}</h3><p>${esc(x.description || '')}</p></div></article>`).join('')}</div></div>` : ''}</div></section>` : ''}
    ${(news.length || events.length) ? `<section class="home-section section-soft" id="updates"><div class="theme-container news-agenda-grid">${news[0] ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Berita Terbaru</p><h2>Informasi terkini seputar kegiatan sekolah.</h2></div><a class="text-link" href="/news">Lihat Semua Berita ${iconMarkup('arrow-right')}</a></div><article class="featured-news"><a href="/news/${encodeURIComponent(news[0].slug || '')}" class="featured-news-media">${news[0].image ? `<img src="${esc(news[0].image)}" alt="${esc(news[0].title || 'Berita sekolah')}" loading="lazy">` : ''}<span>${esc(news[0].category || 'Berita')}</span><div><h3>${esc(news[0].title || 'Berita sekolah')}</h3><p>${esc(news[0].excerpt || news[0].description || '')}</p></div></a><div class="news-side-list">${news.slice(1, 4).map(x => `<a href="/news/${encodeURIComponent(x.slug || '')}"><span>${x.image ? `<img src="${esc(x.image)}" alt="" loading="lazy">` : ''}</span><div><strong>${esc(x.title || '')}</strong><small>${esc(x.published_at || '')}</small></div></a>`).join('')}</div></article></div>` : ''}${events.length ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Agenda Mendatang</p><h2>Jangan lewatkan agenda penting sekolah.</h2></div><a class="text-link" href="#events">Lihat Semua Agenda ${iconMarkup('arrow-right')}</a></div><div class="agenda-list" id="events">${events.slice(0, 4).map(x => `<article class="agenda-item"><time datetime="${esc(x.event_date || '')}"><b>${esc(x.event_date ? new Date(x.event_date).toLocaleDateString('id-ID', {day:'2-digit'}) : '—')}</b><span>${esc(month(x.event_date))}</span></time><div><h3>${esc(x.title || 'Kegiatan sekolah')}</h3><p>${esc(x.time || '')}${x.location ? ` · ${esc(x.location)}` : ''}</p></div>${iconMarkup('chevron-right')}</article>`).join('')}</div></div>` : ''}</div></section>` : ''}
    ${(galleries.length || testimonials.length) ? `<section class="home-section" id="gallery"><div class="theme-container gallery-testimonial-grid">${galleries.length ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Galeri Kegiatan</p><h2>Momen terbaik kami.</h2></div><a class="text-link" href="#gallery">Lihat Galeri Lengkap ${iconMarkup('arrow-right')}</a></div><div class="gallery-home-grid">${galleries.slice(0, 6).map((x, i) => `<a class="gallery-home-item gallery-home-item-${i % 6}" href="#gallery">${x.image ? `<img src="${esc(x.image)}" alt="${esc(x.title || 'Dokumentasi sekolah')}" loading="lazy">` : ''}</a>`).join('')}</div></div>` : ''}${testimonials.length ? `<div><div class="section-head-row compact"><div><p class="section-kicker">Testimoni</p><h2>Apa kata mereka tentang sekolah?</h2></div><a class="text-link" href="#testimonials">Lihat Semua Testimoni ${iconMarkup('arrow-right')}</a></div><div class="testimonial-grid-home" id="testimonials">${testimonials.slice(0, 3).map(x => `<figure class="testimonial-card-home"><blockquote>“${esc(x.quote || x.content || '')}”</blockquote><figcaption>${x.image ? `<img src="${esc(x.image)}" alt="" loading="lazy">` : ''}<span><strong>${esc(x.name || x.author || 'Warga sekolah')}</strong><small>${esc(x.role || '')}</small></span></figcaption><div class="stars">★★★★★</div></figure>`).join('')}</div></div>` : ''}</div></section>` : ''}
    <section class="home-section section-soft" id="documents"><div class="theme-container documents-spmb-grid"><div><div class="section-head-row compact"><div><p class="section-kicker">Pusat Dokumen</p><h2>Unduh dokumen dan formulir penting.</h2></div><a class="text-link" href="/downloads">Lihat Semua Dokumen ${iconMarkup('arrow-right')}</a></div><div class="document-home-list">${downloads.slice(0, 4).map(x => `<a href="${esc(x.url || '#')}" class="document-home-row"><span class="document-file-icon">${iconMarkup('file-text')}</span><span><strong>${esc(x.title || 'Dokumen')}</strong><small>${esc(x.type || x.extension || 'PDF')} · ${esc(x.file_size || x.size || '')}</small></span>${iconMarkup('arrow-up-right')}</a>`).join('')}</div></div><aside class="spmb-home-banner"><div><p class="section-kicker">SPMB 2025/2026</p><h2>Berikan langkah terbaik untuk masa depan gemilang.</h2><p>Pendaftaran peserta didik baru melalui kanal resmi sekolah.</p><a class="button button-accent" href="${esc(state.spmb_url || '#')}">Daftar Sekarang ${iconMarkup('arrow-right')}</a></div>${about.image ? `<img src="${esc(about.image)}" alt="" loading="lazy">` : ''}</aside></div></section>
    <section class="home-contact-strip" id="contact" aria-label="Kontak sekolah"><div class="theme-container contact-strip-grid"><div>${iconMarkup('map-pin')}<span><b>Alamat</b><small>${esc(state.contact_address || '—')}</small></span></div><div>${iconMarkup('phone')}<span><b>Telepon</b><small>${esc(state.contact_phone || '—')}</small></span></div><div>${iconMarkup('mail')}<span><b>Email</b><small>${esc(state.contact_email || '—')}</small></span></div><div>${iconMarkup('clock-3')}<span><b>Jam Layanan</b><small>${esc(state.contact_hours || '—')}</small></span></div></div></section>
  </div>`;
}
function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
